openapi: 3.0.3
info:
  title: Onboarding API
  version: "1.2"
servers:
  - url: http://STD22007.com
paths:
  /students:
    get:
      summary: See the students
      operationId: SeeStudents
      responses:
        "200":
          description: Results
          content:
            application/json:
              schema:
               items:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal Server Error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
    post:
      summary: Make an insertion
      operationId: addStudent
      requestBody:
        description: To create a new student
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                birthdate:
                  format: date
                gender:
                  format: char
              example:
                id: 4
                name: Yrouane
                birthdate: "2001-01-18"
                gender: M

      responses:
        "201":
          description: New student created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  birthdate:
                    format: date
                  gender:
                    format: char
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        username:
          type: string
          example: Rakoto
        birthdate:
          format: date
          
